In [2]:
import pandas as pd

data = iris = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data")

data.head()

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [4]:
data

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   5.1          149 non-null    float64
 1   3.5          149 non-null    float64
 2   1.4          149 non-null    float64
 3   0.2          149 non-null    float64
 4   Iris-setosa  149 non-null    object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB

In [7]:
import pandas as pd
import numpy as np

enroll = 200130107094
print("Enrollment no=",enroll)
df = pd.DataFrame(np.random.randn(8,4),
                  index=['a','b','c','d','o','p','r','s'],
                  columns=['A','B','C','D'])
print(df.loc[:,'A'])

Enrollment no= 200130107094
a    0.251080
b    0.787673
c   -3.025530
d   -0.600817
o   -0.108201
p   -0.705814
r   -0.311349
s    0.750388
Name: A, dtype: float64

In [10]:
import pandas as pd
import numpy as np

enroll = 200130107094
print("Enrollment no=",enroll)
df = pd.DataFrame(np.random.randn(8,4),
                  index=['a','b','c','d','o','p','r','s'],
                  columns=['A','B','C','D'])
print(df.loc[:,['A','C']])

Enrollment no= 200130107094
          A         C
a -0.235767  0.013696
b  0.177512 -0.107896
c  0.556820 -0.608177
d  0.711441 -1.260578
o  0.533142 -1.026267
p -1.610268 -1.488511
r -1.480311  0.180943
s -1.142087 -0.115067

In [11]:
import pandas as pd
import numpy as np

enroll = 200130107094
print("Enrollment no=",enroll)
df = pd.DataFrame(np.random.randn(8,4),
                  index=['a','b','c','d','o','p','r','s'],
                  columns=['A','B','C','D'])
print(df.loc[['a','b','p','r'],['A','C']])

Enrollment no= 200130107094
          A         C
a -0.881793  1.461056
b  0.005636 -0.087069
p  0.328379  0.986206
r -1.633008 -0.787393

In [13]:
import pandas as pd
import numpy as np

enroll = 200130107094
print("Enrollment no=",enroll)
df = pd.DataFrame(np.random.randn(8,4),
                  index=['a','b','c','d','o','p','r','s'],
                  columns=['A','B','C','D'])
print(df.loc['a':'r'])

Enrollment no= 200130107094
          A         B         C         D
a -1.175924  0.500057 -0.671636 -1.464957
b  1.622117 -0.938245 -0.676733  0.400941
c  0.171999  0.218423  1.439993  1.091536
d -1.671518  0.434670 -0.692612 -0.614280
o -1.089817 -1.629374  1.708120 -0.883816
p  0.370458  0.774383  0.498044  0.008154
r  0.186233  0.782491 -1.029260 -0.530986

In [14]:
import pandas as pd
import numpy as np

enroll = 200130107094
print("Enrollment no=",enroll)
df = pd.DataFrame(np.random.randn(8,4),
                  index=['a','b','c','d','o','p','r','s'],
                  columns=['A','B','C','D'])
print(df.loc['a'] > 0)

Enrollment no= 200130107094
A    False
B     True
C    False
D    False
Name: a, dtype: bool

In [15]:
import pandas as pd
import numpy as np

enroll = 200130107094
print("Enrollment no=",enroll)
df = pd.DataFrame(np.random.randn(8,4),
                  index=['a','b','c','d','o','p','r','s'],
                  columns=['A','B','C','D'])
print(df.iloc[:4])

Enrollment no= 200130107094
          A         B         C         D
a -1.791813  0.493810  0.276134 -0.333196
b -0.269628 -0.690568 -0.100157 -0.600764
c  0.890233  1.585978  0.401112  0.664195
d  1.627990  0.036113  0.481364 -0.986470

In [16]:
import pandas as pd
import numpy as np

enroll = 200130107094
print("Enrollment no=",enroll)
df = pd.DataFrame(np.random.randn(8,4),
                  index=['a','b','c','d','o','p','r','s'],
                  columns=['A','B','C','D'])
print(df.iloc[:4])
print(df.iloc[1:5,2:4])

Enrollment no= 200130107094
          A         B         C         D
a  0.030256  1.587390 -1.400796 -1.325972
b -0.992730 -0.341956  0.674136  1.034454
c  1.182369  1.403397  0.638057  0.016584
d -1.430476 -0.450943 -0.780214 -1.092966
          C         D
b  0.674136  1.034454
c  0.638057  0.016584
d -0.780214 -1.092966
o -1.688773  1.357692

In [17]:
print('Enrollment no=',enroll)
data.describe()

Enrollment no= 200130107094

              5.1         3.5         1.4         0.2
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [18]:
print('Enrollment no=',enroll)
data.max()

Enrollment no= 200130107094

5.1                       7.9
3.5                       4.4
1.4                       6.9
0.2                       2.5
Iris-setosa    Iris-virginica
dtype: object

In [19]:
print('Enrollment no=',enroll)
data.min()

Enrollment no= 200130107094

5.1                    4.3
3.5                    2.0
1.4                    1.0
0.2                    0.1
Iris-setosa    Iris-setosa
dtype: object

In [21]:
print('Enrollment no=',enroll)
data.iloc[100:151].mean()

Enrollment no= 200130107094

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.

5.1    6.593878
3.5    2.967347
1.4    5.542857
0.2    2.016327
dtype: float64

In [22]:
print('Enrollment no=',enroll)
data.iloc[100:151].median()

Enrollment no= 200130107094

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.

5.1    6.5
3.5    3.0
1.4    5.5
0.2    2.0
dtype: float64

In [23]:
print('Enrollment no=',enroll)
data.count()

Enrollment no= 200130107094

5.1            149
3.5            149
1.4            149
0.2            149
Iris-setosa    149
dtype: int64

In [24]:
print('Enrollment no=',enroll)
data.std()

Enrollment no= 200130107094

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.

5.1    0.828594
3.5    0.433499
1.4    1.759651
0.2    0.761292
dtype: float64

In [25]:
print('Enrollment no=',enroll)
data.corr()

Enrollment no= 200130107094

          5.1       3.5       1.4       0.2
5.1  1.000000 -0.103784  0.871283  0.816971
3.5 -0.103784  1.000000 -0.415218 -0.350733
1.4  0.871283 -0.415218  1.000000  0.962314
0.2  0.816971 -0.350733  0.962314  1.000000

In [27]:
df = [['Braund, Mr.Owen Harris',80,177.0],['Heikkinen, Miss. Laina',78,180.0],['Monvila, Rev.Juozas',87,165.0]]
df2 = pd.DataFrame(df,columns=['name','other_disease','Height'])
df2

                     name  other_disease  Height
0  Braund, Mr.Owen Harris             80   177.0
1  Heikkinen, Miss. Laina             78   180.0
2     Monvila, Rev.Juozas             87   165.0

In [ ]:
df3 = pd.merge(data,df2,how='right',on='other_disease')
df3